# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Vela Scheduler CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    working-directory: ./go

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: ./go/go.work
        check-latest: true
        cache-dependency-path: ./go/go.work.sum

    - name: Build Scheduler
      run: make build-scheduler

    - name: Build Cluster Agent
      run: make build-cluster-agent
